from enum import StrEnum


class WorkoutReviewStatus(StrEnum):
    PENDING = "pending"
    CLAIMED = "claimed"
    AWAITING_MEMBER_ACCEPTANCE = "awaiting_member_acceptance"
    MEMBER_CHANGES_REQUESTED = "member_changes_requested"
    APPROVED = "approved"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"


EXCLUSIVE_ASSIGNMENT_STATUSES = frozenset(
    {
        WorkoutReviewStatus.CLAIMED,
        WorkoutReviewStatus.AWAITING_MEMBER_ACCEPTANCE,
        WorkoutReviewStatus.MEMBER_CHANGES_REQUESTED,
    }
)


class WorkoutReviewQueueView(StrEnum):
    PENDING = "pending"
    MINE = "mine"
    APPROVED = "approved"


class WorkoutReviewErrorCode(StrEnum):
    COACH_ROLE_REQUIRED = "COACH_ROLE_REQUIRED"
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND"
    REVIEW_NOT_CLAIMED = "REVIEW_NOT_CLAIMED"
    REVIEW_ALREADY_CLAIMED = "REVIEW_ALREADY_CLAIMED"
    REVIEW_LEASE_EXPIRED = "REVIEW_LEASE_EXPIRED"
    STALE_DRAFT_REVISION = "STALE_DRAFT_REVISION"
    INVALID_DRAFT = "INVALID_DRAFT"
    EXERCISE_NOT_ALLOWED = "EXERCISE_NOT_ALLOWED"
    REVIEW_ALREADY_APPROVED = "REVIEW_ALREADY_APPROVED"
    REVIEW_ALREADY_REJECTED = "REVIEW_ALREADY_REJECTED"
    REVIEW_EXPLANATION_REQUIRED = "REVIEW_EXPLANATION_REQUIRED"
    REVIEW_SUPERSEDED = "REVIEW_SUPERSEDED"
    MEMBER_NOT_ALLOWED = "MEMBER_NOT_ALLOWED"
    REVIEW_NOT_AWAITING_MEMBER_ACCEPTANCE = "REVIEW_NOT_AWAITING_MEMBER_ACCEPTANCE"
    REVIEW_PROPOSAL_NOT_FOUND = "REVIEW_PROPOSAL_NOT_FOUND"
