import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { supportCategories, supportCategoryLabels, supportCopy, supportStatuses, supportStatusLabels, type SupportCategory, type SupportStatus, type SupportTicket } from '@fitician/core';
import { SupportLayout } from './SupportPages';
import { adminSupportApi as api } from './api';
export function AdminSupportPage() {
 const {i18n}=useTranslation(),lang=i18n.resolvedLanguage==='en'?'en':'fa',c=supportCopy[lang];
 const [status,setStatus]=useState<SupportStatus|''>('open'),[category,setCategory]=useState<SupportCategory|''>(''),[search,setSearch]=useState(''),[items,setItems]=useState<SupportTicket[]>([]),[count,setCount]=useState(0),[cursor,setCursor]=useState<string|null>(null),[before,setBefore]=useState<string>(),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const epoch=useRef(0);
 useEffect(()=>{const current=++epoch.current;setLoading(true);setError(false);const timer=setTimeout(()=>{void api.list({status:status||undefined,category:category||undefined,search:search.trim(),before}).then(page=>{if(epoch.current!==current)return;setItems(prev=>before?[...new Map([...prev,...page.items].map(t=>[t.id,t])).values()]:page.items);setCount(page.open_count);setCursor(page.older_cursor);setLoading(false);}).catch(()=>{if(epoch.current===current){setError(true);setLoading(false);}});},search?250:0);return()=>{epoch.current=current+1;clearTimeout(timer);};},[status,category,search,before,attempt]);
 return <SupportLayout admin><header className="support-heading"><h1>{c.queue}</h1><div>{c.count}: <strong>{count}</strong></div></header><div className="support-admin-filters"><label>{c.status}<select value={status} onChange={e=>{setBefore(undefined);setItems([]);setStatus(e.target.value as SupportStatus|'');}}><option value="">{c.all}</option>{supportStatuses.map(id=><option key={id} value={id}>{supportStatusLabels[lang][id]}</option>)}</select></label><label>{c.category}<select value={category} onChange={e=>{setBefore(undefined);setItems([]);setCategory(e.target.value as SupportCategory|'');}}><option value="">{c.all}</option>{supportCategories.map(id=><option key={id} value={id}>{supportCategoryLabels[lang][id]}</option>)}</select></label><label>{c.search}<input type="search" value={search} maxLength={160} onChange={e=>{setBefore(undefined);setItems([]);setSearch(e.target.value);}} /></label><button onClick={()=>{setBefore(undefined);setAttempt(a=>a+1);}}>{c.refresh}</button></div>{error&&<p role="alert">{c.error}<button onClick={()=>setAttempt(a=>a+1)}>{c.retry}</button></p>}{loading&&<p role="status">{c.loading}</p>}{!loading&&!error&&!items.length&&<section className="support-empty">{c.noResults}</section>}<div className="support-tickets">{items.map(t=><Link key={t.id} to={`/admin/support/${t.id}`}><div><h2>{t.subject}</h2><span>{supportCategoryLabels[lang][t.category]}</span></div><div><span className="support-status" data-status={t.status}>{supportStatusLabels[lang][t.status]}</span><time dateTime={t.last_activity_at}>{new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(new Date(t.last_activity_at))}</time></div></Link>)}</div>{cursor&&<button disabled={loading} onClick={()=>setBefore(cursor)}>{c.older}</button>}</SupportLayout>;
}
